params:
  cookie_banner:
    enable: false
baseURL: /
defaultContentLanguage: fr
languageCode: fr
languages:
  fr:
    title: Laboratoire de recherche MICA
theme: osuny-hugo-theme
paginate: 18
permalinks:
  pages:          /pages/:slug/
taxonomies:
  administrator:  administrators
  author:         authors
  category:       categories
  researcher:     researchers
  teacher:        teachers
